### ISSUE TITLE
Sources are not well organized.

### ISSUE THREAD

**Issue by Firoso** [uzyfeo/RogueLegacyEnhanced#2]
-Sources are mostly all in "RogueCastle" and not well segregated by namespace.
-Most types are inappropriately named (EnemyObj_Eagle is not a good type name in .NET)

**Comment by uzyfeo** [comment]
Yep, I've seen that too, but it as I stated more or less everywhere - I'm working with quite a big disassembly here :D

There is too many things that could've been done better and I hope they will be done by some time :)
