### ISSUE TITLE
Enemy states are initialized in code.

### ISSUE THREAD

**Issue by Firoso** [uzyfeo/RogueLegacyEnhanced#3]
Enemy state is initialized in sources via convoluted assignment blocks and switch statements.

This should likely stream from embedded resources (prefer json for quick serialization, or xml for readability, schema support, and less reliance on external type providers)

**Comment by uzyfeo** [comment]
I wanted to implement XML files which will store basically all Enemy and other GameObj info to be accessible externally to moders and tools later... Not only its states... 

My plan was to create generalized classes and put all info into XML files.

So I think this will be a part of it :)
